### PR TITLE
Fix: Remove preview warning

### PR DESCRIPTION
**Pull request by TimoWestland**
Fixes: #6

### CODE REVIEW

**Comment by TimoWestland** [comment]
@robbertkauffman this might work as well:
```
    if (hostname === cmsUrls.preview.hostname) {
      return true;
    } else if (hostname !== cmsUrls.live.hostname && process.env.NODE_ENV !== 'production') {
      console.log(`Warning! Could not detect preview mode for ${hostname}. Check if cmsUrls have been properly set. Setting preview to false.`);
    }
```

What do you prefer?

**Comment by robbertkauffman** [comment]
Hi @TimoWestland ,

For some reason your pull request contained some other commits as well. So I created a new branch called debugging and fixed it in bba6300ece1c1fbc4031b2caa98f0a4f439ef3c8, which is published as 0.4.3-rc1.

Unfortunately I can't use process.env.NODE_ENV !== 'production' as it's always 'production', as this is determined at build time of the library. So for now I've just disabled the logging of the error until I find a way to enable 'debug mode' in the library from the React app.

One question though: why are you seeing this error? The error should only be triggered when your live and preview hostname are different (as configured in cmsUrls) and the current hostname doesn't match either the live nor preview hostname. Why is it not matching to the live hostname?

Please close if the new fix resolves the issue.

Best,
Robbert

**Comment by TimoWestland** [comment]
Hi @robbertkauffman,

Thanks for your update. I didn't see all the wrong commits in my PR, sorry! Also makes sense you can't use the NODE_ENV. Maybe just adding an additional param `debug` or something like that to this function might do the trick.

As for why i'm seeing the warning in the first place, our urls look like this:
`live: www-grandvision.test.onehippo.com`
`preview: cms-grandvision.test.onehippo.com`

Which will result in them not matching. I don't really see any other way around this, so we are always seeing the warning.

Anyhow, thanks for the new version! I'm going to test it right away 👍

**Comment by TimoWestland** [comment]
Fix works like a charm, closing this.

**Comment by robbertkauffman** [comment]
@TimoWestland: the warning should have only be logged when the hostname doesn't match both the preview and live configured hostnames. Could it be that there are any other hostname aliases or even IP addresses that are used to access the site?

**Pull request closed without merging**
