### PR TITLE
Add export of ManageContentButton

### LINKED ISSUE #3: Add additional exports of components and utils
During my project implementation with this SDK, I ran into the issue of not having access some utils and components. I think they can be exported because it doesn't add any risk and just can be ignored if the are not needed by implementation.

### PR DESCRIPTION
**Pull request by TimoWestland**
Fixes #3

### CODE REVIEW

**Comment by robbertkauffman** [comment]
Hi Timo,

I can see the use in exporting the ManageContentButton component. However, I'm not quite clear on the use case for getConfigurationForPath. Before I accept, could you clarify the use case for exporting this method?

Thanks!
Robbert

**Comment by TimoWestland** [comment]
Hi Robbert,

I'm currently using it for the wrapper component around my Footer. We try to keep our actual components as decoupled as possible from the CMS. 

```javascript
const CmsFooter = ({ pageModel, preview, staticsUrl }: Props) => {
  const configuration = getConfigurationForPath('footer', pageModel)
  const contentRef = getNestedObject(configuration, ['models', 'document', '$ref'])

  if (!configuration || !contentRef) {
    return null
  }

  const content = getContentByRef(contentRef, pageModel)
  const menu = mapMenuToLinks(configuration.components[0])
  const logo = createImage(content.logo.$ref, pageModel)

  const footerContent = {
    ...content,
    menu,
    logo,
  }

  return (
    <Footer
      staticsUrl={staticsUrl}
      content={footerContent}
    />
  )
}
```

I've tried to do this by using the `<RenderCmsComponent path="footer"/>` which pretty much does the same thing as far as I can see, but this is not working currently. It doesn't give any output, error, warning, nothing. If I can get this to work I won't need the export of the getConfigurationForPath, but I don't know where to look.

**Comment by robbertkauffman** [comment]
What kind of CMS component is the footer (e.g. component, container, container-item? And does the footer component in the CMS have the hst:label property? Could you paste the Page Model API JSON so I can take a look? RenderCmsComponent should render any component you throw at it by path. I rather fix the issue with the RenderCmsComponent rather than exposing the methods used by RenderCmsComponent.

**Comment by TimoWestland** [comment]
The footer is a component and does **not** have the hst:label property. Here is a gist with the API response https://gist.github.com/TimoWestland/5c39bec426dde450d285770d4b6e2fa5.

I agree that it's better to fix the issue in my solution or perhaps the RenderCmsComponent. Do I need to have it in my componentDefinitions maybe? 

I'll change #3 to only export the manage content button

Thanks for the help, really appreciate it 👍

**Comment by robbertkauffman** [comment]
Thanks for posting the API response.

From what I can see you have a static footer component that has its model set. By default, the SDK only outputs container-items, not any parameters or models that are provided on (static) components or containers. Is there a reason why you can't convert the footer to a container, and set the current footer model through a banner component inside the container?

In any case, you should be able to render the menu component that is nested in the footer as followed:
`<RenderCmsComponent path="footer/menu"/>`

Let me know if that works!

**Comment by TimoWestland** [comment]
I've tried to use the RenderCmsComponent for the footer menu and I think it works, but it uses the SDK its menu component which I don't want. I asked @namendes why our footer is not a container component and it's because it's a fixed component (not drag & dropable). 

For now this is OK for me. The header and the footer are very specific so it's okay to have a little wrapper component around it. The real fix here would be to have both the `configuration` and the `content` object supplied when we set `wrapInContentComponent` to `true` in the componentDefinitions, because then we can just wrap all of our components in the contentComponent, and have the manageContentButton supplied as a prop, so the export won't be required anymore.

I've added the ManageContentButton to our source code temporarily untill the fix above is realized. 
You can close this PR if you want.

Thanks for your help anyway 👍

**Comment by namendes** [comment]
In this case, the Footer is a hst:component because we don't want editor to remove it from the page. I was looking in the console to add a label to the component but it is not possible by default. 
I can probably do this by adding a relaxed mixin but is this recommended?

**Comment by robbertkauffman** [comment]
Thanks for clarifying Timo and Nuno!

I'll work on making the RenderCmsComponent more flexible, so that you can use custom menu components, and can use custom components for static components like the footer.

**Comment by robbertkauffman** [comment]
Hi Timo,

I have added support for rendering static components, and exported the `<ManageContentButton>` component class for use in the app. Please note that I've renamed this component to `<CmsEditButton>` as it's more generic now and can also be used to render edit buttons for site menus.

Please see the new branch [static-components](https://github.com/bloomreach/experience-react-sdk/tree/static-components) and 4df7eb6b794532b9123239b1ef3d088c00299b09.

To test it: use the [0.4.0-rc1](https://www.npmjs.com/package/bloomreach-experience-react-sdk/v/0.4.0-rc1) tag that just has been published.

See copy + paste below from the updated readme on usage:

### `<RenderCmsComponent>`

Renders a CMS component and all of its children using the Page Model supplied by `<CmsPage>`. Will 
render the entire Page Model by default.

#### Properties

- `path` - `String` path to a component (static CMS component), container or container-item in the Page 
 Model to render only that component and its children. If no path is supplied, entire Page Model will be 
 rendered. 
- `renderComponent` - `React.Component` render a static CMS component using specified React component. 
 Only works in combination with `path` property, which should specify path to the static CMS component. 
 Site menus that are rendered this way can leverage the `<CmsEditButton>` component for rendering edit 
 buttons in the CMS.

#### Example

```jsx
<RenderCmsComponent path={'menu'} renderComponent={CmsMenu} />
```

### `<CmsEditButton>`

Inserts meta-data for either a content-item or site menu for placing an edit button in preview mode in 
the CMS. Content-items that are rendered by a content component using `wrapInContentComponent: true` do 
not need to use this component, but should use the `manageContentButton` prop that passes the meta-data.

#### Properties

- `configuration` - `Object` configuration of the site menu (not the component configuration containing 
the menu) or the content-item object which has the `_meta` object in its root.
- `preview` - `Boolean` toggle to prevent edit buttons from being rendered outside of preview.


Let me know if this resolves your issue.

Best,
Robbert

**Comment by TimoWestland** [comment]
Hi Robbert, 

This looks great! I'll try to test it as soon as possible 👍

**Comment by TimoWestland** [comment]
Hi Robbert, 

The updated RenderCmsComponent works great. But the CmsEditButton we cannot use yet as we've added something ourselfs that we need now. Have look at this gist: https://gist.github.com/TimoWestland/6dc911609141c39f64d930179b9cab12

We added the possibility to add to pass in styles to the button, to give it a better position in the channel manager. We need this to have all the buttons in the right place. Might you be able to add this to the component too? It's not urgent because we can still use our own for now, but it would be a nice addition in my opinion.

**Comment by robbertkauffman** [comment]
Hi @TimoWestland,

Positioning of the edit button should be done on the overlay element (inserted by the CMS), not on parent element containing the HTML comment (<CmsEditButton/>). This can be done by CSS rules alone:

```css
.title {
  position: relative;
}
.title a.hst-cmseditlink {
  top: 10px;
  right: 10px;
}
```

See for more details https://www.onehippo.org/library/concepts/component-development/position-edit-buttons.html

Best,
Robbert

**Pull request closed without merging**
